Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2018-12, with the labels that each got.

#319 Enable more error reporting in gradle in Jitpack
  jitpack.yml
Labels: App Integration

#327 added replaceBlockAction handling
  src/app/MainApp.js
  src/block-management/block-manager.js
  src/block-management/block-picker.js
Labels: Blocks

#338 use same behavior as Gutenberg web for replacing an empty default block
  src/block-management/block-manager.js
Labels: Blocks

#356 Adding SafeAreaView to block-toolbar component.
  src/block-management/block-toolbar.js
Labels: enhancement

#386 [iOS]: Make post content aware of Safe Areas.
  src/block-management/block-manager.js
Labels: iOS

#385 [Bridge iOS]: Adding isLoading public variable.
  react-native-gutenberg-bridge/ios/Gutenberg.swift
Labels: App Integration, iOS

#397 iOS Only - Re-arrange scroll position of text inputs on landscape mode
  src/components/keyboard-aware-flat-list.android.js
  src/components/keyboard-aware-flat-list.ios.js
Labels: Needs iOS Dev

#396 Sending `editorDidLayout` message to Native Bridge side.
  react-native-gutenberg-bridge/index.js
  react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
  react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.m
  react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
  src/block-management/block-manager.js
  src/block-management/block-toolbar.js
Labels: iOS

#399 Remove block top/bottom padding
  src/block-management/block-holder.js
  src/block-management/block-holder.scss
Labels: Blocks

#410 Add 2px left and right margins to inline toolbar
  src/block-management/inline-toolbar/style.scss
Labels: Needs Design

#407 Add left/right borders to focused block
  src/block-management/block-holder.scss
Labels: Blocks

#413 Adding KeyboardHideButton component.
  src/block-management/block-toolbar.js
  src/components/keyboard-hide-button.js
Labels: Editor Chrome

#414 iOS only - Fix bottom padding of focused block to the keyboard
  __mocks__/styleMock.js
  src/components/keyboard-aware-flat-list.ios.js
Labels: Needs iOS Dev

#431 [Android bridge] Start the RN app only after we got the real post content
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Labels: App Integration

#445 only show Add Block Here indicator when block is not replaceable
  src/block-management/block-manager.js
Labels: enhancement

#454 Block Picker: remove 'replace block' title, only keep 'add block' title
  src/block-management/block-manager.js
  src/block-management/block-picker.js
Labels: Blocks
