Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2018-11, with the labels that each got.

#239 Fix Android back button not dismissing the inserter's block-type picker
  src/block-management/block-picker.js
Labels: bug

#248 Fix Picker touch handling, avoiding to have to touch twice if unfocused
  src/block-management/block-picker.js
Labels: bug

#261 Removing `visible` prop from `BlockPicker`.
  src/block-management/block-manager.js
  src/block-management/block-picker.js
Labels: Writing Flow

#262 Store 3rd party podspecs in the repo
  .gitignore
  bin/generate-podspecs.sh
  react-native-gutenberg-bridge/third-party-podspecs/DoubleConversion.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/Folly.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/glog.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/yoga.podspec.json
Labels: App Integration

#263 Adding doc for making new releases
  docs/Releasing.md
Labels: Documentation

#268 Fix modal animation
  src/block-management/block-picker.js
Labels: Editor Chrome

#300 Create blocks empty by default
  src/block-management/block-manager.js
Labels: Writing Flow

#286 Make block holder and toolbar look nicer
  src/block-management/block-holder.js
  src/block-management/block-holder.scss
  src/block-management/block-manager.js
  src/block-management/colors.scss
  src/block-management/constants.js
  src/block-management/inline-toolbar.js
  src/block-management/inline-toolbar.scss
  src/block-management/inline-toolbar/actions.js
  src/block-management/inline-toolbar/button.js
  src/block-management/inline-toolbar/index.js
  src/block-management/inline-toolbar/style.scss
Labels: Editor Chrome

#305 Create the Android JS bundle only on Travis
  .travis.yml
Labels: App Integration
