Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-02, with the labels that each got.

#538 [iOS] Fix the RichText title.
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
  react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.m
  react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.swift
  src/variables.ios.scss
Labels: iOS

#568 Fixes an issue with the font in the title and placeholder for the title.
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug

#589 Support for the bridge in the android demo app
  android/app/build.gradle
  android/app/src/main/java/com/gutenberg/MainApplication.java
  android/settings.gradle
Labels: Android

#591 Fix placeholder position for RTL layout
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: RTL

#608 Improve style of inserter UI
  src/block-management/block-manager.js
  src/block-management/block-picker.js
  src/block-management/block-picker.scss
Labels: Android, iOS

#611 Fix/Set focus on title for new posts on Android
  jest/setup.js
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
  react-native-gutenberg-bridge/index.js
  src/block-management/block-manager.js
Labels: App Integration

#615 Implement set focus on title.
  ios/gutenberg/GutenbergViewController.swift
  react-native-gutenberg-bridge/ios/Gutenberg.swift
  react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Labels: iOS

#617 Adds support for pasting in iOS.
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
  react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.m
  react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.swift
Labels: enhancement

#619 Avoid sending invalid caret rect information.
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug

#610 Fix dictation issue on iOS
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: iOS

#633 Remove JS handling of title focus
  src/block-management/block-manager.js
Labels: iOS

#536 Use gutenberg translation files locally
  .gitignore
  i18n-cache/.gitignore
  i18n-cache/data/.gitignore
  i18n-cache/index.js
  ios/gutenberg/GutenbergViewController.swift
  package.json
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
  react-native-gutenberg-bridge/ios/Gutenberg.swift
  react-native-gutenberg-bridge/ios/GutenbergBridgeDataSource.swift
  src/app/App.js
  yarn.lock
Labels: Needs Android Dev, Needs iOS Dev, enhancement

#668 Fix `min-height-title` to avoid little but still noticeable glitch
  src/variables.android.scss
Labels: Android
