Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-11, with the labels that each got.

#1523 [Aztec iOS]: `shouldInteractWithURL` will return always false to avoid crashes
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: enhancement, iOS

#1535 Signals the need to relayout view after HTML change.
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug

#1517 Send backspace event to JS in more scenarios
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: iOS

#1541 Issue/fix layout bug in ios 13.2
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bugfix

#1540 Fix iOS13 link tap bug
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug, iOS

#1550 Update debug configuration for VSCode
  .vscode/launch.json
Labels: Tooling

#1539 [iOS] Implement client-defined media options.
  ios/gutenberg/GutenbergViewController.swift
  ios/gutenberg/MediaPickCoordinator.swift
  react-native-gutenberg-bridge/ios/Gutenberg.swift
  react-native-gutenberg-bridge/ios/GutenbergBridgeDataSource.swift
  react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
  react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Labels: Media, enhancement, iOS

#1520 Generate i18n files for WPAndroid and WPiOS to use
  bin/po2android.js
  bin/po2swift.js
  bundle/android/strings.xml
  bundle/ios/GutenbergNativeTranslations.swift
  package.json
  yarn.lock
Labels: App Integration

#1552 Prevents selection after ZWSP character
  RELEASE-NOTES.txt
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: Writing Flow

#1578 Undo more changes related to PRE support
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecTextFormatEnum.java
Labels: Android, bugfix

#1589 Automate gutenberg translations followup
  bin/po2android.js
  bin/po2swift.js
  bundle/android/strings.xml
  bundle/ios/GutenbergNativeTranslations.swift
  package.json
Labels: App Integration

#1600 Remove declaration on bridge of unused methods.
  react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.m
Labels: Technical Debt
