Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-04, with the labels that each got.

#796 Updated recyclerview-list reference
  package.json
  yarn.lock
Labels: Android

#805 Revert some changes to yarn.lock
  yarn.lock
Labels: App Integration

#814 Remove deprecated controls plugin
  src/index.js
Labels: bug

#813 Added manifest merge to enable use of React Native's DevSettings screen
  react-native-gutenberg-bridge/android/src/debug/AndroidManifest.xml
Labels: Android

#752 Adding enzyme to empower unit-tests (with some examples)
  .flowconfig
  __mocks__/styleMock.js
  enzyme.config.js
  jest.config.js
  jest/setup.js
  package.json
  src/__tests__/code.test.js
  src/__tests__/html-text-input-test.js
  src/__tests__/links-ui.test.js
  src/__tests__/paragraph.test.js
  yarn.lock
Labels: Testing, enhancement

#802 Mitigate the problem of moving the current block down sets the caret to the wrong block
  src/block-management/block-holder.js
Labels: Android

#840 Use react-native-cli with the Android debugging fix
  package.json
  yarn.lock
Labels: Android

#812 e2e test improvements
  .circleci/config.yml
  .gitignore
  __device-tests__/blocks/block-interaction.js
  __device-tests__/blocks/paragraph-block-interaction.js
  __device-tests__/gutenberg-editor.test.js
  __device-tests__/helpers/appium-local.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
  bin/example-content/initial-device-tests-html.js
  bin/example-content/initial-html.js
  bin/load-initial-html.sh
  package.json
  src/app/App.js
  src/app/AppContainer.js
  yarn.lock
Labels: Testing

#857 FIX empty block creation on device running AOSP keyboard
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
Labels: bug

#864 Add `requestMediaImport` method to the Android bridge
  android/app/src/main/java/com/gutenberg/MainApplication.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Labels: Android, Media, Paste

#850 818 - Sometimes keyboard suggestions remove the word entirely
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecTextFormatEnum.java
Labels: bug

#868 Use the Aztec-Android version with the #845 fix
  react-native-aztec/android/build.gradle
Labels: bug

#873 Hack: patch Metro to not watch files when bundling
  DependencyGraph.js.patched
  package.json
Labels: Android

#853 Xcode 10.2 compatibility
  .circleci/config.yml
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
Labels: Tooling

#889 [iOS] Deactivate Tab and Shift+Tab key shortcuts
  package.json
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: iOS

#842 Include test reporter for Jest
  .circleci/config.yml
  .gitignore
  jest.config.js
  package.json
  yarn.lock
Labels: Testing

#849 log jobURL at end of successful job
  __device-tests__/helpers/utils.js
Labels: Testing

#927 Improve Screen Reader support for Inner Toolbar
  src/block-management/inline-toolbar/index.js
Labels: Accessibility
