Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-12, with the labels that each got.

#1621 Use plural method for multiple media selection handling
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/Media.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Labels: Android, Media

#1653 Make sure if the textColor is changed the default text color is updated.
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug

#1557 Correct path to the jest binary for test debugger
  package.json
Labels: Tooling

#1657 Update Aztec to fix CI error with xcode 10
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
Labels: Tooling

#1658 Add release notes for Gallery
  RELEASE-NOTES.txt
Labels: Documentation

#1608 Update tests for Xcode 11/iOS 13
  .circleci/config.yml
  __device-tests__/gutenberg-editor-block-insertion.test.js
  __device-tests__/gutenberg-editor-rotation.test.js
  __device-tests__/helpers/caps.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
  package.json
  yarn.lock
Labels: Testing

#1664 Update Getting Started documentation to shorten git commands
  README.md
Labels: Documentation

#1561 Nudge for adding tests, clearer language on the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Tooling

#1576 Basic template picker
  src/index.js
Labels: Page Templates
