Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-08, with the labels that each got.

#1260 Hotfix - 1.10.1 - Update to android aztec v1.3.29
  package.json
  react-native-aztec/android/build.gradle
Labels: Android

#1278 Master v1.10.1 to develop
  package.json
  react-native-aztec/android/build.gradle
Labels: release-process

#1271 Bridge iOS: Add mediaType to appendMedia event.
  react-native-gutenberg-bridge/ios/Gutenberg.swift
Labels: bugfix, iOS

#1306 Fix initial html after changes to text alignment
  src/initial-html.js
Labels: Tooling

#1251 Enforce Prettier (add CI and pre-commit hook)
  babel.config.js
  bin/ci-checks-js.sh
  jest.config.js
  libdefs.js
  package.json
  rn-cli-inside-gb.config.js
  sass-transformer-inside-gb.js
  src/_colors.scss
  src/index.js
  src/index.test.js
  src/jsdom-patches.js
  yarn.lock
Labels: Tooling

#1322 Update Aztec iOS to v1.8.1
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
Labels: enhancement
