Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-09, with the labels that each got.

#1336 Try/device tests
  __device-tests__/gutenberg-editor-block-insertion.test.js
  __device-tests__/gutenberg-editor-heading.test.js
  __device-tests__/gutenberg-editor-image.test.js
  __device-tests__/gutenberg-editor-lists-end.test.js
  __device-tests__/gutenberg-editor-lists.test.js
  __device-tests__/gutenberg-editor-paragraph.test.js
  __device-tests__/gutenberg-editor-paste.test.js
  __device-tests__/gutenberg-editor-rotatation.test.js
  __device-tests__/helpers/caps.js
Labels: Testing

#1352 [iOS]Fix: Oddly formatted text hangs Gutenberg
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: Writing Flow, iOS

#1374 Only report selection changes if text view is still first responder.
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug

#1382 Work around for link selection.
  package.json
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug
