Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-05, with the labels that each got.

#943 Address list design review on iOS
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
  react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.swift
Labels: Needs Design Review, bug

#948 Fix move selected text on iOS
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
  react-native-aztec/src/AztecView.js
Labels: Needs Android Dev, bugfix, iOS

#944 Add instructions for running simulator with other iOS devices to README
  README.md
Labels: Documentation, iOS

#964 CircleCI: Limit max Jest and Flow workers to avoid memory errors
  .flowconfig
  bin/ci-checks-js.sh
Labels: Tooling

#905 Remove duplicated imagepipeline-okhttp3 dependency
  react-native-gutenberg-bridge/android/build.gradle
Labels: bug

#983 Use AztecAndroid's v1.3.27 tag
  react-native-aztec/android/build.gradle
Labels: Android

#982 Add release notes file
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE.md
  RELEASE-NOTES.txt
Labels: Documentation

#993 Update Aztec-iOS to 1.6.3 in the demo app
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
Labels: Tooling

#970 Add list block test
  __device-tests__/gutenberg-editor-lists.test.js
  __device-tests__/helpers/test-data.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
  android/app/src/main/java/com/gutenberg/MainApplication.java
  package.json
  src/components/html-text-input.js
Labels: Blocks, Testing

#821 Add paragraph block writing flow tests
  __device-tests__/blocks/block-interaction.js
  __device-tests__/blocks/paragraph-block-interaction.js
  __device-tests__/gutenberg-editor-lists.test.js
  __device-tests__/gutenberg-editor.test.js
  __device-tests__/helpers/appium-local.js
  __device-tests__/helpers/test-data.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
  android/app/src/main/java/com/gutenberg/MainApplication.java
  package.json
  src/block-management/block-holder.js
  src/block-management/block-manager.js
  src/block-management/inline-toolbar/index.js
  src/components/html-text-input.js
  yarn.lock
Labels: Testing

#1016 Re-load the ReactVideoPackage that got removed by #821
  android/app/src/main/java/com/gutenberg/MainApplication.java
Labels: Android

#1012 Fix react hook error on block selection
  rn-cli.config.js
Labels: bugfix

#991 Nested lists
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: Blocks

#1025 Update README to point to project Wiki for UI tests
  README.md
Labels: enhancement

#1024 Follow web side's lead to add `indexToSelect` to onReplace
  src/block-management/block-holder.js
Labels: bugfix

#1026 Update default versions used in CI
  __device-tests__/helpers/caps.js
Labels: Testing

#1035 Update Aztec version to 1.6.5
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
Labels: bug

#1038 Focus blocks on Android Device Tests
  __device-tests__/gutenberg-editor-lists-end.test.js
  __device-tests__/gutenberg-editor-lists.test.js
  __device-tests__/gutenberg-editor.test.js
  package.json
Labels: Testing, bugfix
