Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-07, with the labels that each got.

#1183 Reduce iOS bridge logging
  ios/gutenberg/GutenbergViewController.swift
  react-native-gutenberg-bridge/ios/Gutenberg.swift
  react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
  react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Labels: enhancement, iOS

#1189 CircleCI: Better yarn caching
  .circleci/config.yml
Labels: Tooling

#1188 CircleCI: Speed up iOS device tests by caching gutenberg.app
  .circleci/config.yml
Labels: Testing

#1210 Update react-native-svg version
  package.json
  react-native-gutenberg-bridge/third-party-podspecs/RNSVG.podspec.json
  yarn.lock
Labels: iOS

#1207 Fixed flaky issues with Android device tests
  __device-tests__/gutenberg-editor-rotatation.test.js
  __device-tests__/helpers/utils.js
Labels: Testing

#1060 Add image block tests
  __device-tests__/gutenberg-editor-image.test.js
  __device-tests__/helpers/test-data.js
  __device-tests__/pages/editor-page.js
Labels: Testing

#1181 [Low pri] Fix build for node v12.4.0
  README.md
  package.json
  src/globals.js
  src/jsdom-patches.js
  yarn.lock
Labels: bugfix

#1069 Add heading block test
  __device-tests__/gutenberg-editor-heading.test.js
  __device-tests__/helpers/test-data.js
  __device-tests__/pages/editor-page.js
Labels: Testing

#1112 Experiment - Android X migration
  Gutenberg.podspec
  RNTAztecView.podspec
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  bin/generate-podspecs.sh
  ios/gutenberg.xcodeproj/project.pbxproj
  package.json
  react-native-aztec/.gitignore
  react-native-aztec/android/build.gradle
  react-native-aztec/android/gradle.properties
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecTextShadowNode.java
  react-native-gutenberg-bridge/android/build.gradle
  react-native-gutenberg-bridge/android/gradle.properties
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
  react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge-Bridging-Header.h
  react-native-gutenberg-bridge/third-party-podspecs/DoubleConversion.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/Folly.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/RNReactNativeRecyclerviewList.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/RNSVG.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-ART.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-Core.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-DevSupport.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-Fabric.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTActionSheet.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTAnimation.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTBlob.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTCameraRoll.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTFabric.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTImage.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTLinking.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTNetwork.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTPushNotification.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTSettings.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTTest.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTText.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTVibration.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-RCTWebSocket.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-cxxreact.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-graphics.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-jscallinvoker.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-jsi.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-jsiexecutor.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-jsinspector.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-turbomodule-core.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React-turbomodule-samples.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/React.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/glog.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/react-native-keyboard-aware-scroll-view.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/react-native-safe-area.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/react-native-video.podspec.json
  react-native-gutenberg-bridge/third-party-podspecs/yoga.podspec.json
  yarn.lock
Labels: Android, iOS

#1139 Add block insertion tests
  .circleci/config.yml
  __device-tests__/gutenberg-editor-block-insertion.test.js
  __device-tests__/gutenberg-editor-heading.test.js
  __device-tests__/gutenberg-editor-image.test.js
  __device-tests__/gutenberg-editor-lists-end.test.js
  __device-tests__/gutenberg-editor-lists.test.js
  __device-tests__/gutenberg-editor-paragraph.test.js
  __device-tests__/gutenberg-editor-paste.test.js
  __device-tests__/gutenberg-editor-rotatation.test.js
  __device-tests__/helpers/caps.js
  __device-tests__/helpers/test-data.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
  bin/sauce-pre-upload.sh
  package.json
Labels: Testing

#1223 Add device test documentation to README
  README.md
  __device-tests__/CONTRIBUTING.md
  __device-tests__/README.md
Labels: Documentation

#1230 Remove references to node 9 errors in readme
  README.md
Labels: Documentation
