Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2019-06, with the labels that each got.

#1050 Update Aztec reference.
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
Labels: iOS

#1056 FIX NPE in WPAndroidGlue while setting Auth header
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/OkHttpHeaderInterceptor.java
Labels: Android

#1065 Avoid sending onEnter when AztecView is not focused.
  RELEASE-NOTES.txt
  react-native-aztec/src/AztecView.js
Labels: bugfix

#1080 Add html verification on iOS
  __device-tests__/gutenberg-editor-paragraph.test.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
Labels: Testing

#1090 Remove drag-drop text interaction from Aztec-iOS wrapper
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug, iOS

#1096 Do not intercept delete when there is a range selection.
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug

#1083 Implement jsdom node traversal properties
  src/jsdom-patches.js
Labels: Paste, bugfix

#1097 Issue/1045 paste of attributed strings
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug

#1093 Implement the shadow node for proper laying out Aztec on Android
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecTextShadowNode.java
Labels: Android

#1109 Hardcode link text color in Android
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
Labels: Android

#1108 Improve copy paste of lists
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: enhancement

#1115 Copy i18n-cache folder too on publishing to Bintray
  bin/update-bintray-repo.sh
Labels: Tooling

#1102 Add device rotation tests
  __device-tests__/gutenberg-editor-paragraph.test.js
  __device-tests__/gutenberg-editor-rotatation.test.js
  __device-tests__/helpers/test-data.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
Labels: Testing

#1100 Add Paste UI Tests for Android
  __device-tests__/gutenberg-editor-paste.test.js
  __device-tests__/helpers/test-data.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
Labels: Android, Paste, Testing

#1125 Fix Android device tests for AndroidX migration
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
  ios/gutenberg.xcodeproj/project.pbxproj
Labels: Android, Testing

#1129 Removes empty lines lists and quotes
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug, iOS

#1144 Change Aztec to not send changes notification when not user related
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: enhancement

#1180 Run device tests across available instances on CI
  package.json
Labels: Testing
