Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-03, with the labels that each got.

#1964 Fix crash pasting HTML with wrapped images.
  RELEASE-NOTES.txt
Labels: Paste, bugfix

#2042 Feat: change dimmed style opacity for InnerBlocks
  RELEASE-NOTES.txt
Labels: InnerBlocks, Needs Design Review

#2078 Test Aztec 1.17.1
  RNTAztecView.podspec
  ios/Podfile
  ios/Podfile.lock
Labels: bug
