Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-06, with the labels that each got.

#2340 Update podfile.
  ios/Podfile.lock
Labels: release-process

#2346 Add contributing file.
  CONTRIBUTING.md
Labels: Documentation

#2359 Add Release Checklist
  docs/Releasing.md
Labels: release-process

#2211 Use Kotlin in react-native-gutenberg-bridge
  android/app/src/main/java/com/gutenberg/MainApplication.java
  android/app/src/main/java/com/gutenberg/Media.java
  android/build.gradle
  react-native-aztec/android/build.gradle
  react-native-gutenberg-bridge/android/build.gradle
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNMedia.kt
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/Media.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/Media.kt
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Labels: [Pri] Low, [Type] Technical Debt

#2362 Update the VS code search settings to that seaching is easier
  .vscode/settings.json
Labels: Tooling, [Pri] Low, [Status] Needs Code Review

#2366 Queue Events for better media uploads
  react-native-gutenberg-bridge/ios/Gutenberg.swift
  react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Labels: bugfix

#2442 Update steps to reflect the mono repo organization
  docs/Releasing.md
Labels: release-process

#2422 Add Release notes doc
  .github/PULL_REQUEST_TEMPLATE.md
  docs/Release-notes.md
Labels: Documentation, [Pri] Low, [Status] Needs Copy Review, release-process
