Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-11, with the labels that each got.

#2770 Stories block: hide/show based on Editor capability settings being set, only after it's been loaded
  src/jetpack-editor-setup.js
Labels: Story block, Testing

#2765 Update release checklist template
  docs/Releasing.md
Labels: release-process

#2766 Move the setupJetpackEditor() call order
  src/index.js
Labels: Jetpack, Story block

#2776 Update prerequisites in README
  README.md
Labels: Documentation

#2684 Fix "ENOMEM: not enough memory, write" error on CI with Android E2E tests
  .circleci/config.yml
Labels: Testing

#2764 Add git submodule dep updates via Dependabot
  .github/dependabot.yml
Labels: Tooling

#2781 Add yarn as a dev dependency
  package-lock.json
  package.json
Labels: Tooling

#2795 Stories: moved __DEV__ flag to contact-info block availability declaration only
  src/jetpack-editor-setup.js
Labels: Jetpack, Story block
