Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-01, with the labels that each got.

#1709 Handle empty media selection for file not found case
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
Labels: Android, Media, bugfix

#1732 Move DependencyGraph.js so the original file is not left over after `yarn bundle`
  package.json
Labels: Technical Debt

#1707 Add very basic "add gallery block" UI test
  __device-tests__/gutenberg-editor-gallery.test.js
  __device-tests__/pages/editor-page.js
Labels: Blocks, Testing

#1756 Fix - Media Text: media acts like video even if I upload jpg
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/Media.java
Labels: Android, bug

#1637 Do no escape strings with double quotes in android strings.xml
  bin/po2android.js
  package.json
Labels: i18n

#1710 Release v1.19.1
  package.json
  react-native-aztec/android/build.gradle
Labels: enhancement, release-process

#1768 Force the react-native-video fork to build against same RN version as gutenberg-mobile from maven repo
  package.json
  yarn.lock
Labels: Android

#1786 Hardcode Android RN version in bridge and aztec
  react-native-aztec/android/build.gradle
  react-native-gutenberg-bridge/android/build.gradle
Labels: bug

#1775 Update aztec to 1.15.0
  ios/gutenberg.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  react-native-aztec/ios/Cartfile
  react-native-aztec/ios/Cartfile.resolved
  react-native-aztec/ios/RNTAztecView.xcodeproj/project.pbxproj
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: enhancement

#1797 [iOS] Remove xcworkspace.
  ios/gutenberg.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: Tooling

#1666 Fix broken link in Getting Started documentation
  README.md
Labels: Documentation

#1820 Rename iOS module name of sample app from gutenberg to GutenbergDemo.
  .circleci/config.yml
  __device-tests__/helpers/utils.js
  ios/gutenberg.xcodeproj/project.pbxproj
  ios/gutenberg.xcodeproj/xcshareddata/xcschemes/gutenberg.xcscheme
  package.json
Labels: Tooling

#1813 Android e2e test flakiness fix
  __device-tests__/gutenberg-editor-paragraph.test.js
  __device-tests__/helpers/utils.js
  __device-tests__/pages/editor-page.js
Labels: Testing

#1826 Update ref to react-native-slider fork to support autolinking
  ios/Podfile.lock
  ios/gutenberg.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: Crash, bugfix

#1828 Remove DEV flag from Media Editor button
  react-native-gutenberg-bridge/index.js
Labels: DO NOT MERGE, Media, Task

#1847 Remove DEV flag from Media Editor button
  react-native-gutenberg-bridge/index.js
Labels: Media, Task

#1686 Adding retry feature to mobile apiFetch handler
  android/app/src/main/java/com/gutenberg/MainApplication.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/RequestExecutor.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
  src/api-fetch-setup.js
Labels: enhancement

#1806 Added list block ordered button e2e test
  __device-tests__/gutenberg-editor-lists.test.js
  __device-tests__/helpers/test-data.js
  __device-tests__/pages/editor-page.js
Labels: Testing
