Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-05, with the labels that each got.

#2215 Bump version number in package.json to 1.27.0
  ios/Podfile.lock
  package.json
Labels: release-process

#2212 Add code of conduct file.
  CODE_OF_CONDUCT.md
Labels: Documentation

#2226 Issue/update aztec ios to 1.19.0
  RELEASE-NOTES.txt
  RNTAztecView.podspec
  ios/Podfile.lock
  src/initial-html.js
Labels: [Type] Enhancement

#2251 Fix release notes
  RELEASE-NOTES.txt
Labels: release-process

#2137 [UI tests] Run canaries on a PR and optionally full suite
  .circleci/config.yml
  __device-tests__/gutenberg-editor-heading.test.js
  __device-tests__/gutenberg-editor-image.test.js
  __device-tests__/gutenberg-editor-lists.test.js
  package.json
Labels: Testing

#2306 Update initial HTML.
  src/initial-html.js
Labels: [Type] Enhancement

#2305 Delete temporary RN tools before building
  react-native-gutenberg-bridge/android/build.gradle
Labels: App Integration

#2309 Update Appium version to 1.16.0
  __device-tests__/helpers/caps.js
Labels: Testing

#2266 Display radial gradient in block which supporting gradients
  RELEASE-NOTES.txt
Labels: [Type] Enhancement

#2318 Update Aztec to version 1.19.2
  ios/Podfile
  ios/Podfile.lock
Labels: [Type] Bug

#2322 Update to official version of Aztec 1.19.2
  RNTAztecView.podspec
  ios/Podfile
  ios/Podfile.lock
Labels: release-process
