Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-04, with the labels that each got.

#2060 Add tests for Latest-Posts Bock
  __device-tests__/gutenberg-editor-latest-posts.test.js
  __device-tests__/pages/editor-page.js
  src/initial-html.js
  src/test/api-fetch-setup.test.js
Labels: Testing

#2097 New template for release PRs
  .github/PULL_REQUEST_TEMPLATE/release_pull_request.md
Labels: release-process

#2080 Accept multiple headers through OnAuthHeaderRequestedListener
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/OkHttpHeaderInterceptor.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Labels: Android, Needs Android review

#2148 Fixes Latests Posts Tests by expanding the scroll to button functionality
  __device-tests__/gutenberg-editor-latest-posts.test.js
  __device-tests__/pages/editor-page.js
Labels: Testing

#2124 Update react-native-video dependency to remove Apache 2.0 dependencies
  package.json
  yarn.lock
Labels: .com/.org code separation

#2127 Issue/1966 Disable whitespace collapse in Aztec
  RELEASE-NOTES.txt
  RNTAztecView.podspec
  ios/Podfile
  ios/Podfile.lock
  react-native-aztec/android/build.gradle
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: Needs Android Dev, bug

#2051 [UI tests] Simplify helper functions usage
  __device-tests__/gutenberg-editor-block-insertion.test.js
  __device-tests__/gutenberg-editor-gallery.test.js
  __device-tests__/gutenberg-editor-heading.test.js
  __device-tests__/gutenberg-editor-image.test.js
  __device-tests__/gutenberg-editor-lists-end.test.js
  __device-tests__/gutenberg-editor-lists.test.js
  __device-tests__/gutenberg-editor-paragraph.test.js
  __device-tests__/gutenberg-editor-paste.test.js
  __device-tests__/gutenberg-editor-rotation.test.js
  __device-tests__/helpers/test-data.js
  __device-tests__/pages/editor-page.js
Labels: Testing

#2115 [UI tests] Schedule runs for full UI tests suite
  .circleci/config.yml
Labels: Testing

#2141 Correct android font weight
  src/index.js
  src/text-font-weight-correct.js
Labels: Android, bugfix
