Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-02, with the labels that each got.

#1874 Schedule to request focus instead of asking immediately
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
Labels: Android, bugfix

#1926 Remove duplicate gallery image size release note
  RELEASE-NOTES.txt
Labels: release-process

#1925 e2e test update ios simulators versions
  __device-tests__/helpers/caps.js
  __device-tests__/helpers/utils.js
Labels: Testing

#1938 Issue/1916 fix align issues
  RELEASE-NOTES.txt
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bug

#1842 Avoid fullscreen text entry UI in landscape mode
  RELEASE-NOTES.txt
  react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
Labels: Android, Needs Design Review, bugfix

#1944 Update readme
  README.md
Labels: Documentation

#1946 Update release notes
  RELEASE-NOTES.txt
Labels: release-process

#1951 Update podfile.lock file to latest version.
  ios/Podfile.lock
Labels: release-process

#1943 Remove BlockModel var and prop.
  react-native-aztec/ios/RNTAztecView/BlockFormatHandler.swift
  react-native-aztec/ios/RNTAztecView/BlockModel.swift
  react-native-aztec/ios/RNTAztecView/HeadingBlockFormatHandler.swift
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
  react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.m
Labels: Technical Debt

#1945 [Android] Add logging to Page Template Picker
  android/app/src/main/java/com/gutenberg/MainApplication.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
  react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Labels: Analytics, enhancement

#1969 [iOS] Fix [Obj] character after dictation
  react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Labels: bugfix
