Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-10, with the labels that each got.

#2676 Clarify that milestones are not required in release checklist
  docs/Releasing.md
Labels: release-process

#2705 Fix: only set initialData with demo initialHtml example if initialData not set
  src/index.js
Labels: [Type] Bug, bugfix

#2739 Add Yarn to README Prerequisites
  README.md
Labels: Jetpack
