Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2020-09, with the labels that each got.

#2595 Use the latest version of the RNCMaskedView Podspec
  third-party-podspecs/RNCMaskedView.podspec.json
Labels: [Type] Bug

#2650 Updating package-lock.json
  package-lock.json
Labels: Tooling

#2558 Improve release script
  bin/release_automation.sh
  docs/Releasing.md
Labels: release-process

#2664 Add CI Check for package-lock.json diffs
  .circleci/config.yml
  bin/ci-checks-js.sh
Labels: Tooling
