Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2021-06, with the labels that each got.

#3116 Add a "Set as Featured Image" Button to Image Block (Android Only)
  RELEASE-NOTES.txt
Labels: [Status] In Progress, [Type] Enhancement

#3576 Update WPAndroid Integration guide for publishing to S3 changes
  WPAndroid Integration.md
Labels: Tooling

#3601 Shallow clone project for CI tasks
  .circleci/config.yml
Labels: Testing, Tooling

#3624 CI fetches commit reference directly
  .circleci/config.yml
Labels: Testing, Tooling

#3660 Remove yarn
  package-lock.json
  package.json
  yarn.lock
Labels: Tooling

#3659 Fix Gutenberg Mobile dependencies resolution
  metro.config.js
  package-lock.json
  package.json
Labels: [Type] Bug
