Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2021-03, with the labels that each got.

#3223 Adds .swiftlint.yml to disable the localization_comment rule from Hound
  .swiftlint.yml
Labels: Tooling

#3254 Add release notes merged PR - Remove cancel button from settings options
  RELEASE-NOTES.txt
Labels: Documentation

#2914 Fix a broken image in README
  README.md
Labels: Documentation

#3262 Adds WPAndroid Integration document
  WPAndroid Integration.md
Labels: Documentation

#3307 Disable NPM version 7
  .circleci/config.yml
  README.md
  package.json
Labels: Web breakage
