Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2021-09, with the labels that each got.

#3990 Fix error "nvm not found" in CircleCI workflows
  .circleci/config.yml
Labels: [Type] Bug

#4016 Add nvmrc file to specify node version
  .buildkite/pipeline.yml
  .circleci/config.yml
  .nvmrc
  README.md
Labels: Documentation, Tooling

#4036 Release 1.61.2
  RELEASE-NOTES.txt
Labels: release-process
