Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2021-08, with the labels that each got.

#3717 Add command for forcing the i18n cache to get updated
  package.json
Labels: release-process

#3761 Enforce to use the node version specified by Gutenberg on CircleCI workflows
  .circleci/config.yml
Labels: [Type] Bug

#3791 Temporarily update Buildkite android docker image to 'latest'
  .buildkite/pipeline.yml
Labels: Tooling

#3794 Update Buildkite Android Docker image to v1.1.0
  .buildkite/pipeline.yml
Labels: Tooling

#3801 Update README.md
  README.md
Labels: Documentation

#3810 Bundle local static React Native assets for Android
  .buildkite/publish-react-native-bridge-android-artifacts.sh
Labels: [OS] Android, Tooling

#3831 Merge release 1.58.3 to trunk
  RELEASE-NOTES.txt
Labels: release-process

#3837 Merge release 1.59.1 to develop
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: release-process
