Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2022-01, with the labels that each got.

#4426 Feature/android workflow
  .github/workflows/sync-android.yml
  bin/sync-android.sh
  package.json
Labels: App Integration, [OS] Android, release-process, sync:android

#4455 Add i18n documentation
  README.md
Labels: Documentation

#4469 Add clean i18n cache command
  .gitignore
  package.json
  src/i18n-cache/.gitignore
Labels: [Type] Enhancement

#4474 Force check i18n cache when cleaning project
  package.json
Labels: [Type] Bug

#4464 Fix missing Featured Image translations
  RELEASE-NOTES.txt
  bundle/android/strings.xml
  bundle/ios/GutenbergNativeTranslations.swift
Labels: [OS] Android, i18n

#4476 Ignore local environment .tool-versions configuration file
  .gitignore
Labels: [Type] Task

#4478 Assure destination directory presence for localization strings files output
  bin/strings2android.js
  bin/strings2swift.js
Labels: [Type] Enhancement

#4484 Improve string replacements for android lint rules in `strings2android` script
  bin/strings2android.js
  bundle/android/strings.xml
Labels: [Type] Enhancement, i18n

#4462 Fix headings of i18n section in README
  README.md
Labels: Documentation

#4401 Remove unused JSON asset files
  bundle/ios/assets/gutenberg/packages/blocks/src/api/i18n-block.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ar.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/bg.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/bo.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ca.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/cs.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/cy.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/da.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/de.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/el.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-au.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-ca.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-gb.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-nz.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-za.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es-ar.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es-cl.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es-cr.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/fa.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/fr.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/gl.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/he.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/hr.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/hu.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/id.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/is.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/it.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ja.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ka.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ko.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/nb.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/nl-be.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/nl.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/pl.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/pt-br.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/pt.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ro.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ru.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/sk.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/sq.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/sr.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/sv.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/th.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/tr.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/uk.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ur.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/vi.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/zh-cn.json
  bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/zh-tw.json
  bundle/ios/assets/jetpack/projects/plugins/jetpack/extensions/index.json
Labels: [Type] Task, i18n
