Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2023-07, with the labels that each got.

#5967 Remove unneeded fix for text font-weight style
  src/setup.js
  src/text-font-weight-correct.js
Labels: [OS] Android

#5986 RN upgrade: Fix test suite 1 errors
  __device-tests__/gutenberg-editor-sanity-test-1-visual.test.js
Labels: Testing

#5993 Update Android Docker Image to add JDK 17 support
  .buildkite/pipeline.yml
Labels: Tooling
