Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2023-06, with the labels that each got.

#5826 Add set caption integration test of VideoPress block
  src/test/videopress/__snapshots__/edit.js.snap
  src/test/videopress/edit.js
Labels: Testing, VideoPress block

#5892 Update README.md for additional Device Test instructions
  README.md
Labels: Documentation

#5916 Fix VideoPress block test cases
  src/test/videopress/__snapshots__/edit.js.snap
  src/test/videopress/edit.js
  src/test/videopress/local-helpers/constants.js
  src/test/videopress/local-helpers/utils.js
Labels: Testing
