Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2023-08, with the labels that each got.

#6025 Only run `prebundle` command when building from Git tag
  .buildkite/pipeline.yml
Labels: [Type] Enhancement, Tooling

#6032 Upload composed source maps to Buildkite
  .buildkite/pipeline.yml
Labels: Tooling

#6030 Add symbolicate stack trace script
  bin/symbolicate-stracktrace.sh
Labels: Tooling

#6038 Add crop option when taking a screenshot in e2e tests
  __device-tests__/utils.js
Labels: Testing

#6054 Simplify dependency tree with `npm dedupe`
  package-lock.json
Labels: Tooling

#6141 Update Social icons snapshots
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-1-visual-test-js-gutenberg-editor-test-suite-1-social-icons-block-should-display-active-icon-colors-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-1-visual-test-js-gutenberg-editor-test-suite-1-social-icons-block-should-display-active-icon-colors-1-ios.png
Labels: Testing
