Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2023-05, with the labels that each got.

#5715 Add initial VideoPress test for Android
  jest.config.js
  src/test/videopress/edit.js
Labels: VideoPress block

#5772 Update VideoPress block support from dev-only to iOS-only
  src/block-support/supported-blocks.json
Labels: Documentation

#5751 VideoPress block: Initial setting tests
  jest.config.js
  src/test/videopress/__snapshots__/edit.js.snap
  src/test/videopress/edit.js
  src/test/videopress/local-helpers/constants.js
  src/test/videopress/local-helpers/utils.js
Labels: Testing, VideoPress block

#5773 ci: Remove WordPress-Android sync tag trigger
  .github/workflows/sync-android.yml
Labels: [Type] Technical Debt, Tooling

#5795 Remove test case from Test Suite 4
  __device-tests__/gutenberg-editor-sanity-test-4-visual.test.js
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-link-from-the-clipboard-is-presented-as-an-option-in-the-link-picker-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-link-from-the-clipboard-is-presented-as-an-option-in-the-link-picker-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-link-from-the-clipboard-is-presented-as-an-option-in-the-link-picker-2-android.png
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-link-from-the-clipboard-is-presented-as-an-option-in-the-link-picker-2-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-link-from-the-clipboard-is-presented-as-an-option-in-the-link-picker-3-android.png
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-link-from-the-clipboard-is-presented-as-an-option-in-the-link-picker-3-ios.png
Labels: Testing

#5819 Exclude `ios-xcframework` folder when resolving modules in Metro
  metro.config.js
Labels: [Type] Bug
