Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2023-10, with the labels that each got.

#6180 Update .ruby-version to 3.2.2
  ios-xcframework/.ruby-version
  ios-xcframework/Gemfile
  ios-xcframework/Gemfile.lock
  ios-xcframework/Podfile.lock
Labels: Tooling, ruby

#6253 Revert Skip Buildkite steps for branches for dependabot PRs
  .buildkite/pipeline.yml
Labels: Testing

#6287 Update E2E tests bundle script for iOS
  .buildkite/commands/build-ios.sh
  __device-tests__/image-snapshots/gutenberg-editor-unsupported-block-visual-test-js-gutenberg-editor-visual-test-for-unsupported-block-should-be-able-to-open-the-unsupported-block-web-view-editor-1-ios.png
  package.json
Labels: Testing

#6292 Update Functionality Test: Themes for Appium 2
  __device-tests__/gutenberg-editor-functionality-test-themes-visual.test.js
Labels: Testing

#6284 test: Update Horizontal Layout test for Appium 2
  __device-tests__/gutenberg-editor-horizontal-layouts-@ipad.test.js
  __device-tests__/image-snapshots/gutenberg-editor-horizontal-layouts-ipad-test-js-gutenberg-editor-i-pad-visual-test-for-horizontal-layouts-should-show-the-right-columns-placeholders-and-alignments-case-1-2-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-horizontal-layouts-ipad-test-js-gutenberg-editor-i-pad-visual-test-for-horizontal-layouts-should-show-the-right-columns-placeholders-and-alignments-case-2-2-ios.png
Labels: Testing, [Type] Task

#6290 Update Functionality Test 1 for Appium 2
  __device-tests__/gutenberg-editor-functionality-test-1-visual.test.js
Labels: Testing

#6300 Update annotate_test_failures to only send Slack notification for trunk merges
  .buildkite/commands/test-ios.sh
Labels: Tooling

#6306 Classic block: Add option to convert to blocks
  RELEASE-NOTES.txt
  bundle/android/strings.xml
  bundle/ios/GutenbergNativeTranslations.swift
Labels: [Type] Enhancement

#6312 Update second Gutenberg Mobile package reference in `package-lock.json`
  package-lock.json
Labels: release-process
