Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2023-04, with the labels that each got.

#5649 VideoPress block: POST support for `wpcom/v2/videopress/meta` endpoint
  src/setup.js
Labels: Jetpack, VideoPress block

#5689 Disable `npm` configuration parameter `engine-strict` when installing dependencies of Jetpack
  bin/install-jetpack.sh
Labels: [Type] Bug, Tooling

#5667 Add script for running `pnpm` commands in Jetpack repo
  .gitignore
  bin/run-jetpack-command.sh
  package.json
Labels: [Type] Enhancement, Tooling
