Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2023-09, with the labels that each got.

#6135 Update Buttons block dark mode screenshot to reduce failures in E2E tests
  __device-tests__/gutenberg-editor-sanity-test-4-visual.test.js
  __device-tests__/image-snapshots/gutenberg-editor-sanity-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-render-dark-mode-colors-1-android.png
  __device-tests__/utils.js
Labels: [Type] Bug, Testing

#6164 Rename tests to use "functionality"
  __device-tests__/gutenberg-editor-functionality-test-1-visual.test.js
  __device-tests__/gutenberg-editor-functionality-test-4-visual.test.js
Labels: Testing

#6169 Rename snapshot tests.
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-allows-deep-nesting-to-at-least-3-levels-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-allows-deep-nesting-to-at-least-3-levels-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-correctly-in-portrait-and-landscape-orientations-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-correctly-in-portrait-and-landscape-orientations-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-correctly-in-portrait-and-landscape-orientations-2-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-correctly-in-portrait-and-landscape-orientations-2-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-placeholders-when-unselected-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-placeholders-when-unselected-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-placeholders-when-unselected-2-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-placeholders-when-unselected-2-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-with-correct-colors-with-dark-mode-enabled-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-with-correct-colors-with-dark-mode-enabled-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-with-correct-colors-with-dark-mode-enabled-2-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-displays-with-correct-colors-with-dark-mode-enabled-2-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-mover-buttons-display-in-the-correct-positions-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-mover-buttons-display-in-the-correct-positions-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-mover-buttons-display-in-the-correct-positions-2-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-mover-buttons-display-in-the-correct-positions-2-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-sliders-display-proportionate-fill-level-previews-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-columns-block-sliders-display-proportionate-fill-level-previews-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-social-icons-block-should-display-active-icon-colors-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-social-icons-block-should-display-active-icon-colors-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-social-icons-block-should-display-the-block-outline-of-a-block-inserted-from-the-appender-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-1-visual-test-js-gutenberg-editor-test-suite-1-social-icons-block-should-display-the-block-outline-of-a-block-inserted-from-the-appender-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-allow-edit-text-styles-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-allow-edit-text-styles-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-have-its-selection-caret-with-the-same-color-as-the-font-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-have-its-selection-caret-with-the-same-color-as-the-font-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-render-custom-text-and-background-color-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-render-custom-text-and-background-color-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-render-dark-mode-colors-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-render-dark-mode-colors-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-render-gradient-background-color-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-buttons-block-should-render-gradient-background-color-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-navigate-between-nested-blocks-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-navigate-between-nested-blocks-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-navigate-between-nested-blocks-2-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-navigate-between-nested-blocks-2-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-navigate-between-nested-blocks-3-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-navigate-between-nested-blocks-3-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-render-dark-mode-colors-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-render-dark-mode-colors-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-traverse-up-and-down-nested-blocks-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-traverse-up-and-down-nested-blocks-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-traverse-up-and-down-nested-blocks-2-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-traverse-up-and-down-nested-blocks-2-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-traverse-up-and-down-nested-blocks-3-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-traverse-up-and-down-nested-blocks-3-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-traverse-up-and-down-nested-blocks-4-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-group-block-should-traverse-up-and-down-nested-blocks-4-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-spacer-block-should-render-dark-mode-colors-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-spacer-block-should-render-dark-mode-colors-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-spacer-block-should-render-proper-alignment-and-spacing-in-landscape-orientation-1-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-spacer-block-should-render-proper-alignment-and-spacing-in-landscape-orientation-1-ios.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-spacer-block-should-render-proper-alignment-and-spacing-in-landscape-orientation-2-android.png
  __device-tests__/image-snapshots/gutenberg-editor-functionality-test-4-visual-test-js-gutenberg-editor-test-suite-4-spacer-block-should-render-proper-alignment-and-spacing-in-landscape-orientation-2-ios.png
Labels: Testing

#6200 Read `RNTAztecView.podspec` from its source in Gutenberg
  RNTAztecView.podspec
  ios-xcframework/Podfile
  ios-xcframework/Podfile.lock
Labels: Tooling

#6234 CircleCI config - Remove iOS jobs
  .circleci/config.yml
Labels: Testing, Tooling
