Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2024-02, with the labels that each got.

#6624 Update metro config for bundles
  package.json
Labels: Tooling

#6627 build: Fix iOS XCFramework failure
  ios-xcframework/XCFrameworkScaffold.xcodeproj/project.pbxproj
Labels: [OS] iOS, Tooling, [Type] Task

#6666 build: XCFramework includes local resources
  ios-xcframework/XCFrameworkScaffold.xcodeproj/project.pbxproj
Labels: Unsupported Block Editor
