Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2024-03, with the labels that each got.

#6515 Update WP iOS Integration documentation with updated XCFramework steps
  WPiOS Integration.md
Labels: Documentation

#6700 build: Fix i18n script paths causing `bundle` command not found errors
  bin/i18n-update.sh
Labels: [Type] Technical Debt, i18n

#6704 build: Fix i18n test script path
  bin/i18n-update.sh
Labels: [Type] Technical Debt, i18n

#6708 build: Capture core dependency updates
  package-lock.json
Labels: [Type] Task

#6715 build: Fix failure when running npm command `i18n:update`
  bin/i18n-update.sh
Labels: [Type] Bug, i18n

#6695 Adopt an optimistic approach in CI to get faster feedback
  .buildkite/pipeline.yml
Labels: Tooling

#6741 Update dependabot configuration to check for updates for each submodule at a different time
  .github/dependabot.yml
Labels: Tooling

#6745 Update Dependabot config to use target-branch for one of the configurations.
  .github/dependabot.yml
Labels: Tooling

#6751 Dependabot config - Use "allow" option for filtering
  .github/dependabot.yml
Labels: Tooling

#6742 Try --maxsockets flag to limit ECONNRESET failures
  .buildkite/commands/install-node-dependencies.sh
Labels: Tooling

#6760 Avoid including source map file in app's binary
  ios-xcframework/XCFrameworkScaffold.xcodeproj/project.pbxproj
  ios-xcframework/build.sh
  ios-xcframework/podspec.erb
Labels: [OS] iOS, Tooling
