Repository wordpress-mobile/gutenberg-mobile, pull requests merged in 2024-01, with the labels that each got.

#6527 docs: Clarify the use of Gutenberg and Gutenberg Mobile repository names
  README.md
Labels: Documentation

#6534 docs: Link to React Native CLI documentation
  README.md
Labels: Documentation, [Type] Task

#6476 Add instructions for providing Aztec commit number in `ios-xcframework`
  WPiOS Integration.md
  ios-xcframework/Podfile
  ios-xcframework/Podfile.lock
Labels: Documentation

#6579 Increase node max available memory in `Build JS Bundles` job
  .buildkite/pipeline.yml
Labels: [Type] Bug, Tooling

#6582 [CI] Fix missing `php` command when building JS bundles for a GitHub tag
  .buildkite/pipeline.yml
Labels: [Type] Bug, Tooling

#6589 build: Capture upgrades from Gutenberg core
  package-lock.json
Labels: dependencies, [Type] Task
